### ISSUE TITLE
Please push semantic version tag

### ISSUE THREAD

**Issue by baccenfutter** [mitchellh/go-homedir#11]
This package turns out to be a dependency of https://github.com/ipfs/go-ipfs. I am in the process of packaging IPFS for Gentoo where we prefer to build our software from source when we install it. Thus I am also packaging this project and would kindly like to ask you to push a semantic version tag, which makes things a lot easier for me.

**Comment by baccenfutter** [comment]
ping

**Comment by baccenfutter** [comment]
https://help.github.com/articles/creating-releases/

**Comment by moleculezz** [comment]
Having similar problem with homebrew for Mac

**Comment by leighmcculloch** [comment]
@baccenfutter Now that Go 1.6 supports vendoring out of the box, what about using that for ipfs instead of Godep and a semantic version number?

**Comment by stapelberg** [comment]
The `dep` tool, which is intended to be folded into the official Go tooling in the future, also uses semver. I think adopting semver is worthwhile.

**Comment by damianoneill** [comment]
@mitchellh as above could you please tag this repo.

**Comment by fd0** [comment]
Oh, 16 days ago the tag `v1.0.0` has been published, so we can probably close this issue.

**Comment by mitchellh** [comment]
Yes, sorry for this, but I was waiting for official reasons to use tagging and seeing what the official Go policy would be. This was done as soon as gomod was announced.
