### ISSUE TITLE
Prefer USERPROFILE over HOMEDRIVE/HOMEPATH

### ISSUE THREAD

**Issue by mbrancato** [mitchellh/go-homedir#23]
I originally opened this in a downstream terraform provider including `go-homedir` as a dependency. The main issue is that HOMEDRIVE/HOMEPATH are relics of NT4 and not standard environment variables post Windows Vista. They appear to exist sometimes in environments with a history of roaming profiles.

You may read the explanation in the original issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1395 

This document has a table of standard environment variables on Windows: https://msdn.microsoft.com/en-us/library/dd378457(v=vs.85).aspx

https://github.com/mitchellh/go-homedir/blob/3864e76763d94a6df2f9960b16a20a33da9f9a66/homedir.go#L138-L155

**Comment by mitchellh** [comment]
This makes sense to me! Thanks for pointing it out.
