### ISSUE TITLE
Does this work on plan9?

### ISSUE THREAD

**Issue by ncw** [mitchellh/go-homedir#3]
I'd like to use this library as one of my users has run into the OSX issue mentioned in the README.

I currently build plan9 binaries - is it likely to work there?

Thanks

Nick

**Comment by tianon** [comment]
This thread is a little old, but I'd point out https://github.com/mitchellh/go-homedir/blob/df55a15e5ce646808815381b3db47a8c66ea62f4/homedir.go#L40-L45, and that the answer is probably that yes, this should work pretty well on plan9. :smile:

**Comment by ncw** [comment]
@tianon thanks!

**Comment by mitchellh** [comment]
Closing since this seems answered :)
